const musicContainer = document.getElementById('music-container');
const playBtn = document.getElementById('play');
const prevBtn = document.getElementById('prev');
const nextBtn = document.getElementById('next');

const audio = document.getElementById('audio');
const progress = document.getElementById('progress');
const progressContainer = document.getElementById('progress-container');
const title = document.getElementById('title');
const cover = document.getElementById('cover');


// Song titles
const songs = ['7G Rainbow Colony (2004)/Idhu Porkkalama.mp3',
    '7G Rainbow Colony (2004)/January Madham.mp3',
    '7G Rainbow Colony (2004)/Kan Peasum Varthaigal.mp3',
    '7G Rainbow Colony (2004)/Kanaa Kaanum Kaalangal II.mp3',
    '7G Rainbow Colony (2004)/Kanaa Kaanum Kaalangal.mp3',
    '7G Rainbow Colony (2004)/Music of Joy.mp3',
    '7G Rainbow Colony (2004)/Naam Vayathukku.mp3',
    '7G Rainbow Colony (2004)/Ninaithu Ninaithu Parthal.mp3',
    '7G Rainbow Colony (2004)/Ninaithu Ninaithu Parthen II.mp3',
    '7G Rainbow Colony (2004)/Walking Through The Rainbow.mp3',
    'Aadhalal Kadhal Seiveer (2012)/Alai Paayum.mp3',
    'Aadhalal Kadhal Seiveer (2012)/Mella Sirithal.mp3',
    'Aadhalal Kadhal Seiveer (2012)/Poovum Poovum.mp3',
    'Aadhalal Kadhal Seiveer (2012)/Thappu Thanda.mp3',
    'Aegan (2008)/Hey Baby.mp3',
    'Aegan (2008)/Hey Salaa.mp3',
    'Aegan (2008)/HeySalaa (Repeat).mp3',
    'Aegan (2008)/Kichu Kichu.mp3',
    'Aegan (2008)/Odum Varayil.mp3',
    'Aegan (2008)/Yahoo Yahoo.mp3',
    'Aethiree (2004)/Bottle Mani.mp3',
    'Aethiree (2004)/Ichu Thariya.mp3',
    'Aethiree (2004)/Kadhal Vandhu.mp3',
    'Aethiree (2004)/Mudhal Mudhalaga.mp3',
    'Aethiree (2004)/Podu Nanba Sakka Podu.mp3',
    'Aethiree (2004)/Saithane Saithane.mp3',
    'Aethiree (2004)/Thamizhnaatu Pennai.mp3',
    'Agaram (2005)/AdadaAdada.mp3',
    'Agaram (2005)/LineKidachichey.mp3',
    'Agaram (2005)/PonnuThotta.mp3',
    'Agaram (2005)/TopuEhiriPogum.mp3',
    'Agaram (2005)/UnnaiNaanPaarthen.mp3',
    'Ameerin Aadhi Baghavan (2012)/Agadam Bagadam.mp3',
    'Ameerin Aadhi Baghavan (2012)/Baghavan Rap.mp3',
    'Ameerin Aadhi Baghavan (2012)/Eisalaamey Eisalaam.mp3',
    'Ameerin Aadhi Baghavan (2012)/Kaatriley Nadanthene.mp3',
    'Ameerin Aadhi Baghavan (2012)/Oru Thuli Vishamaai.mp3',
    'Ameerin Aadhi Baghavan (2012)/Yaavum Poithaanaa.mp3',
    'Anjaan (2014)/Bang Bang Bang.mp3',
    'Anjaan (2014)/Ek Do Theen.mp3',
    'Anjaan (2014)/Kadhal Aasai.mp3',
    'Anjaan (2014)/Oru Kan Jaadai.mp3',
    'Anjaan (2014)/Sirippu En.mp3',
    'April Maadhathil (2002)/Azhagaana Aangal.mp3',
    'April Maadhathil (2002)/Kanavugal Pookum.mp3',
    'April Maadhathil (2002)/Manase Manase.mp3',
    'April Maadhathil (2002)/Poi Solla Intha Manasukku.mp3',
    'April Maadhathil (2002)/Sight Adipom.mp3',
    'April Maadhathil (2002)/Yea Nenjea.mp3',
    'Aravindhan (1996)/All The Best.mp3',
    'Aravindhan (1996)/Eera Nila.mp3',
    'Aravindhan (1996)/Love Is A Magic.mp3',
    'Aravindhan (1996)/Povattum.mp3',
    'Aravindhan (1996)/Poyhum Pothum.mp3',
    'Arinthum Ariyamalum (2005)/Konjam Konjam.mp3',
    'Arinthum Ariyamalum (2005)/Sil Sil.mp3',
    'Arinthum Ariyamalum (2005)/Theepidika.mp3',
    'Arinthum Ariyamalum (2005)/Yela Yela.mp3',
    'Arinthum Ariyamalum (2005)/Yen Kannodu.mp3',
    'Arrambam (2013)/Adadada Aarambame.mp3',
    'Arrambam (2013)/En Fuse Pochu.mp3',
    'Arrambam (2013)/Hare Rama.mp3',
    'Arrambam (2013)/Melala Vedikkudhu.mp3',
    'Arrambam (2013)/Stylish Thamizhachi.mp3',
    'Avan Ivan (2011)/Adi Kavakara Kiliye.mp3',
    'Avan Ivan (2011)/Avanapathi.mp3',
    'Avan Ivan (2011)/Dia Dia Dole.mp3',
    'Avan Ivan (2011)/Mudhal Murai.mp3',
    'Avan Ivan (2011)/Oru Malayoram.mp3',
    'Avan Ivan (2011)/Rasathi Pola.mp3',
    'Avan Ivan (2011)/Rasathi-A Different Start.mp3',
    'Azhagai Irukkirai Bayamai Irukkirathu (2006)/Elaiudhir Kaalam.mp3',
    'Azhagai Irukkirai Bayamai Irukkirathu (2006)/Kadhalai.mp3',
    'Azhagai Irukkirai Bayamai Irukkirathu (2006)/Kanavae.mp3',
    'Azhagai Irukkirai Bayamai Irukkirathu (2006)/Odivaa Kadhale.mp3',
    'Azhagai Irukkirai Bayamai Irukkirathu (2006)/Orampo Naina.mp3',
    'Baana Kaathadi (2010)/En Nenjil.mp3',
    'Baana Kaathadi (2010)/Kupathu Rajakal.mp3',
    'Baana Kaathadi (2010)/Paitheyam Pedikuthu.mp3',
    'Baana Kaathadi (2010)/Thaakkuthe.mp3',
    'Baana Kaathadi (2010)/Ullara Poondhu.mp3',
    'Bala (2002)/Bailamo.mp3',
    'Bala (2002)/Enn Kannai.mp3',
    'Bala (2002)/Poo Poovai Punnagai.mp3',
    'Bala (2002)/Poo Poovai.mp3',
    'Bala (2002)/Theendi Theendi.mp3',
    'Bala (2002)/Vannathi Poochi.mp3',
    'Billa (2007)/Billa Theme Music.mp3',
    'Billa (2007)/My Name Is Billa.mp3',
    'Billa (2007)/Naan Meendum Naanaga.mp3',
    'Billa (2007)/Sei Ethavathu Sei.mp3',
    'Billa (2007)/Seval Kodi.mp3',
    'Billa (2007)/Vethalaiya Potendi.mp3',
    'Billa II (2012)/Billa 2 Theme Music.mp3',
    'Billa II (2012)/Gangster.mp3',
    'Billa II (2012)/Idhayam.mp3',
    'Billa II (2012)/Madurai Ponnu.mp3',
    'Billa II (2012)/Unakkulle Mirugam.mp3',
    'Billa II (2012)/Yedho Mayakkam.mp3',
    'Biriyani (2013)/Briyani.mp3',
    'Biriyani (2013)/Edhirthu Nil.mp3',
    'Biriyani (2013)/Mississippi.mp3',
    'Biriyani (2013)/Nahnh Na Nah (Extended Dance Mix).mp3',
    'Biriyani (2013)/Nahnh Na Nah (New Jack Swing Mix).mp3',
    'Biriyani (2013)/Nahnh Na Nah.mp3',
    'Biriyani (2013)/Pom Pom Penne.mp3',
    'Biriyani (2013)/Run For your Life.mp3',
    'Bose (2004)/Bommalattam.mp3',
    'Bose (2004)/Doli Doli.mp3',
    'Bose (2004)/Enna Enna.mp3',
    'Bose (2004)/Nijama Nijama.mp3',
    'Bose (2004)/Vaitha Kann.mp3',
    'Boss Engira Bhaskaran (2010)/Ada Boss Boss.mp3',
    'Boss Engira Bhaskaran (2010)/Iyley Iyley.mp3',
    'Boss Engira Bhaskaran (2010)/Mama Mama.mp3',
    'Boss Engira Bhaskaran (2010)/Thathi Thaavum Paper Naan.mp3',
    'Boss Engira Bhaskaran (2010)/Yaar Intha Penthan.mp3',
    'Chennai 600028 (2007)/Jalsa (Remix).mp3',
    'Chennai 600028 (2007)/Jalsa Pannungada.mp3',
    'Chennai 600028 (2007)/Natpukullae Oru.mp3',
    'Chennai 600028 (2007)/Oh Oh Ennammo.mp3',
    'Chennai 600028 (2007)/Saroja Saman Nikalo.mp3',
    'Chennai 600028 (2007)/Ulla vaa (World Cup).mp3',
    'Chennai 600028 (2007)/Un Paarvai Mele Pattal.mp3',
    'Chennai 600028 (2007)/Yaaro (Friendship).mp3',
    'Chennai 600028 (2007)/Yaaro Yarukkul (Love).mp3',
    'Daas (2005)/Ennoda Raasi.mp3',
    'Daas (2005)/Nee Enthan.mp3',
    'Daas (2005)/Saami Kittay.mp3',
    'Daas (2005)/Sakka Podu Pottane.mp3',
    'Daas (2005)/Shaheeba Shaheeba.mp3',
    'Daas (2005)/Vaa Vaa.mp3',
    'Deepavali (2007)/Dhol Baaje.mp3',
    'Deepavali (2007)/Kadhal Vaithu.mp3',
    'Deepavali (2007)/Kannan Varum Velai.mp3',
    'Deepavali (2007)/Pogathey Pogathe.mp3',
    'Deepavali (2007)/Thoduven Thoduven.mp3',
    'Dheena (2000)/En Nenjil Ningalane.mp3',
    'Dheena (2000)/Kathal Website Ondru.mp3',
    'Dheena (2000)/Nee Illai Enral.mp3',
    'Dheena (2000)/Sollamal Thottu Chellum Thendral.mp3',
    'Dheena (2000)/Vathikuchi Pathikadhuda.mp3',
    'Goa (2010)/Adida Nayaandiya.mp3',
    'Goa (2010)/Goa (Club Mix).mp3',
    'Goa (2010)/Goa.mp3',
    'Goa (2010)/Idaivazhi Oru.mp3',
    'Goa (2010)/Idhu Varai.mp3',
    'Goa (2010)/Kaadal Endral.mp3',
    'Goa (2010)/Ooru Nalla Ooru.mp3',
    'Goa (2010)/Vaaliba Vaa Vaa.mp3',
    'Goa (2010)/Yeleu Thalamuakkum.mp3',
    'Govindudu Andarivadele (2014)/01 - Neeli Rangu Cheeralona.mp3',
    'Govindudu Andarivadele (2014)/02 - Gulabi Kallu Rendu Mullu.mp3',
    'Govindudu Andarivadele (2014)/03 - Ra Rakumara.mp3',
    'Govindudu Andarivadele (2014)/04 - Prathichota Nake Swagatham.mp3',
    'Govindudu Andarivadele (2014)/05 - Bavagari Choope.mp3',
    'Govindudu Andarivadele (2014)/06 - Kokkokodi.mp3',
    'Idam Porul Yaeval (2014)/Atthuvaana Kattuku.mp3',
    'Idam Porul Yaeval (2014)/Eerakkaathae.mp3',
    'Idam Porul Yaeval (2014)/Endha Vazhi.mp3',
    'Idam Porul Yaeval (2014)/Kondaatamae.mp3',
    'Idam Porul Yaeval (2014)/Kurunthogai.mp3',
    'Idam Porul Yaeval (2014)/Vaiyambatti.mp3',
    'Jai (2012)/Dinam Dinam.mp3',
    'Jai (2012)/Jaan Pillayanalum.mp3',
    'Jai (2012)/Nee Thadai Thadai Thandinaal II.mp3',
    'Jai (2012)/Nee Thadai Thadai Thandinaal.mp3',
    'Jai (2012)/Nila Nila.mp3',
    'Jai (2012)/Vaida Kai Vaida.mp3',
    'Junior Senior (2002)/Anandham Pennukulle.mp3',
    'Junior Senior (2002)/Naan Oruvan.mp3',
    'Junior Senior (2002)/Oh Shalalala Jamaai.mp3',
    'Junior Senior (2002)/Pudhusai Pudhusai.mp3',
    'Junior Senior (2002)/Singara Kanna.mp3',
    'Junior Senior (2002)/Thithippa Iruppa.mp3',
    'Kaadhal Kondein (2003)/18 Vayathil.mp3',
    'Kaadhal Kondein (2003)/Devathayai Kanden.mp3',
    'Kaadhal Kondein (2003)/Kadhal Konden.mp3',
    'Kaadhal Kondein (2003)/Kadhal Mattum Purivathillai.mp3',
    'Kaadhal Kondein (2003)/Manasu Rendum.mp3',
    'Kaadhal Kondein (2003)/Natpinilae Natpinilae.mp3',
    'Kaadhal Kondein (2003)/Nenjodu Kalinthidu.mp3',
    'Kaadhal Kondein (2003)/Thathi Thathi Thaavuthey.mp3',
    'Kaadhal Kondein (2003)/Thodamale Oru Parvai.mp3',
    'Kaadhal Kondein (2003)/Thottu Thottu.mp3',
    'Kaadhal Kondein (2003)/Unnai Thozhi Enbatha.mp3',
    'Kaadhal Solla Vandhen (2010)/Anbulla Sandhya.mp3',
    'Kaadhal Solla Vandhen (2010)/Enna Enna Aagiraen.mp3',
    'Kaadhal Solla Vandhen (2010)/Oh Shala.mp3',
    'Kaadhal Solla Vandhen (2010)/Oru Vaanavillin Pakkathilae.mp3',
    'Kaadhal Solla Vandhen (2010)/Saami Varuguthu.mp3',
    'Kaadhal Solla Vandhen (2010)/Yedho Ondru Unnai.mp3',
    'Kadhal 2 Kalyanam (2011)/Ennakaaga Unnakaaga.mp3',
    'Kadhal 2 Kalyanam (2011)/Ithu Kadhalai Irinthidumo.mp3',
    'Kadhal 2 Kalyanam (2011)/Naa Vetta Pora Aadu.mp3',
    'Kadhal 2 Kalyanam (2011)/Natpin Kathaigalai.mp3',
    'Kadhal 2 Kalyanam (2011)/Thedi Varuven.mp3',
    'Kadhal 2 Kalyanam (2011)/Vellai Kodi.mp3',
    'Kadhal Samrajyam (2002)/Bombay City.mp3',
    'Kadhal Samrajyam (2002)/Chithanna Vasal.mp3',
    'Kadhal Samrajyam (2002)/Iru Kankal Sollum.mp3',
    'Kadhal Samrajyam (2002)/Kalluri Padam.mp3',
    'Kadhal Samrajyam (2002)/Mullaipoo.mp3',
    'Kadhal Samrajyam (2002)/Saisa.mp3',
    'Kadhal Samrajyam (2002)/Thozha Thozha.mp3',
    'Kadhal Samrajyam (2002)/Vidinchankka Kalyanam.mp3',
    'Kalvanin Kadhali (2005)/Eno Kangal.mp3',
    'Kalvanin Kadhali (2005)/Iva Kattil Nattu.mp3',
    'Kalvanin Kadhali (2005)/Kudakkooli Koduthachu.mp3',
    'Kalvanin Kadhali (2005)/Tajmahal Oviya Kadhal.mp3',
    'Kalvanin Kadhali (2005)/Uyir Piriyum Valiyai.mp3',
    'Kalyana Galatta (1998)/Aadham Yevaal.mp3',
    'Kalyana Galatta (1998)/Adiye Kuruvamma.mp3',
    'Kalyana Galatta (1998)/Kummalam Kumba.mp3',
    'Kalyana Galatta (1998)/Madona Paattu.mp3',
    'Kalyana Galatta (1998)/Vazhkaiyil.mp3',
    'Kalyana Galatta (1998)/Velli Malai Kattu.mp3',
    'Kanda Naal Mudhal (2005)/Erimalai Naane.mp3',
    'Kanda Naal Mudhal (2005)/Kanda Naal Mudhalai (Bit).mp3',
    'Kanda Naal Mudhal (2005)/Kanda Naal Mudhalai.mp3',
    'Kanda Naal Mudhal (2005)/Koo Koovena.mp3',
    'Kanda Naal Mudhal (2005)/Merke Merke.mp3',
    'Kanda Naal Mudhal (2005)/Pani Thuli.mp3',
    'Kanda Naal Mudhal (2005)/Pushing It Hard.mp3',
    'Kannamoochi Yenada (2007)/Andru Vandhadhum (Remix).mp3',
    'Kannamoochi Yenada (2007)/Kanna Moochi Attam.mp3',
    'Kannamoochi Yenada (2007)/Megam Megam.mp3',
    'Kannamoochi Yenada (2007)/Putham Pudhu Kaathu.mp3',
    'Kannamoochi Yenada (2007)/Sanjaram.mp3',
    'Kattradhu Thamizh (2007)/Innum Oru Iravu.mp3',
    'Kattradhu Thamizh (2007)/Para Para Pattaampoochi.mp3',
    'Kattradhu Thamizh (2007)/Paravaye Engu Irukirai.mp3',
    'Kattradhu Thamizh (2007)/Unakagathanae,Intha.mp3',
    'Kattradhu Thamizh (2007)/Vaazhkai Enbathu.mp3',
    'Kazhugu (2011)/Aambalaikum Pombalaikum.mp3',
    'Kazhugu (2011)/Aathadi Manasudhan Fem.mp3',
    'Kazhugu (2011)/Aathadi Manasudhan.mp3',
    'Kazhugu (2011)/Paathagathi Kannupattu.mp3',
    'Kazhugu (2011)/Vaadi Vaadi.mp3',
    'Kedi (2006)/Aadhivasi Naane.mp3',
    'Kedi (2006)/Antha Vaanam Pola.mp3',
    'Kedi (2006)/Chumma Chumma.mp3',
    'Kedi (2006)/College Life Da.mp3',
    'Kedi (2006)/College Life.mp3',
    'Kedi (2006)/Kedi Paiya.mp3',
    'Kedi (2006)/Kungama Poovae.mp3',
    'Kedi (2006)/Kungumam Kalainthathe.mp3',
    'Kedi (2006)/Unna Petha Aathaa.mp3',
    'Kedi Billa Killadi Ranga (2013)/Dheivangal Ellaam.mp3',
    'Kedi Billa Killadi Ranga (2013)/Konjum Kili.mp3',
    'Kedi Billa Killadi Ranga (2013)/Oru Porambokku.mp3',
    'Kedi Billa Killadi Ranga (2013)/Sudasuda Thooral.mp3',
    'Kedi Billa Killadi Ranga (2013)/Ulladha Naan.mp3',
    'Kunguma Poovum Konjum Puravum (2009)/Chinnan Sirisu.mp3',
    'Kunguma Poovum Konjum Puravum (2009)/Kadaloram - Yuvan.mp3',
    'Kunguma Poovum Konjum Puravum (2009)/Kadaloram.mp3',
    'Kunguma Poovum Konjum Puravum (2009)/Muttathu Pakkathil.mp3',
    'Kunguma Poovum Konjum Puravum (2009)/Na Dharmanda.mp3',
    'Kunguma Poovum Konjum Puravum (2009)/Orunimisham.mp3',
    'Kurumbu (2003)/Aasai Nooru Vagai.mp3',
    'Kurumbu (2003)/Adhichi Pudhichi II.mp3',
    'Kurumbu (2003)/Adichchi Pudichchi.mp3',
    'Kurumbu (2003)/Kingini Mingin.mp3',
    'Kurumbu (2003)/Kurumbu Kurumbu.mp3',
    'Kurumbu (2003)/Oviya Un Ora Parvai.mp3',
    'Kurumbu (2003)/Theme Music Sax Bit.mp3',
    'Kurumbu (2003)/Vaa Masakaatre.mp3',
    'Machakaaran (2007)/Jegiruthanda.mp3',
    'Machakaaran (2007)/Nee Nee Nee.mp3',
    'Machakaaran (2007)/Nellayela Manadutha.mp3',
    'Machakaaran (2007)/Vanathayum Megathayum.mp3',
    'Machakaaran (2007)/Vayasu Ponnukku.mp3',
    'Manadhai Thirudivittai (2001)/All Day Jolly.mp3',
    'Manadhai Thirudivittai (2001)/Azhagana Suriyan.mp3',
    'Manadhai Thirudivittai (2001)/Color Color.mp3',
    'Manadhai Thirudivittai (2001)/Kutti Kutti.mp3',
    'Manadhai Thirudivittai (2001)/Manjakatu Maina.mp3',
    'Manadhai Thirudivittai (2001)/Sadugudu.mp3',
    'Mankatha (2011)/Balle Lakka.mp3',
    'Mankatha (2011)/Machi Open The Bottle.mp3',
    'Mankatha (2011)/Mankatha Theme Music.mp3',
    'Mankatha (2011)/Nanbane.mp3',
    'Mankatha (2011)/Nee Naan.mp3',
    'Mankatha (2011)/Vaada Bin Laada.mp3',
    'Mankatha (2011)/Vilayadu Mangatha (Extended Dance Mix).mp3',
    'Mankatha (2011)/Vilayadu Mangatha.mp3',
    'Manmadhan (2004)/En Aasai Mythiliye.mp3',
    'Manmadhan (2004)/Kadhal Valarthen.mp3',
    'Manmadhan (2004)/Manmadhane Nee.mp3',
    'Manmadhan (2004)/Om Magire.mp3',
    'Manmadhan (2004)/Thathai Thathai.mp3',
    'Manmadhan (2004)/Vaanamunna.mp3',
    'Masss (2015)/Con Man Theme.mp3',
    'Masss (2015)/Masss Theme.mp3',
    'Masss (2015)/Naan Aval Illai.mp3',
    'Masss (2015)/Piravi.mp3',
    'Masss (2015)/Poochandi.mp3',
    'Masss (2015)/Therikkudhu Masss (Mix).mp3',
    'Masss (2015)/Therikkudhu Masss.mp3',
    'Moondru Per Moondru Kaadhal (2012)/Aaha Kaadhal Konji Pesudhe.mp3',
    'Moondru Per Moondru Kaadhal (2012)/Kaadhal Enthan Kaadhal.mp3',
    'Moondru Per Moondru Kaadhal (2012)/Mazhai Mazhai.mp3',
    'Moondru Per Moondru Kaadhal (2012)/Padapadakkudhu Maname.mp3',
    'Moondru Per Moondru Kaadhal (2012)/Stop The Paatu.mp3',
    'Moondru Per Moondru Kaadhal (2012)/Unakkagave Uyir Vaalgiren.mp3',
    'Mounam Pesiyadhe (2002)/Aadatha Aatamellam.mp3',
    'Mounam Pesiyadhe (2002)/Arupadhu Aayidichu.mp3',
    'Mounam Pesiyadhe (2002)/Chinna Chinnathai Penne.mp3',
    'Mounam Pesiyadhe (2002)/Eh Nanbane Kopam.mp3',
    'Mounam Pesiyadhe (2002)/En Anbae En Anbae.mp3',
    'Mounam Pesiyadhe (2002)/Ilamai Oorai Sutrum.mp3',
    'Mounam Pesiyadhe (2002)/Kannil Kanthamey Vendam.mp3',
    'Mounam Pesiyadhe (2002)/Love All Day Theme Music.mp3',
    'Muthirai (2009)/Azhagana Neeyum.mp3',
    'Muthirai (2009)/July Madhathil.mp3',
    'Muthirai (2009)/Nenjukkulla.mp3',
    'Muthirai (2009)/Night Is Still Young Remix.mp3',
    'Muthirai (2009)/Night Is Still Young.mp3',
    'Muthirai (2009)/Om Shanthi Om Remix.mp3',
    'Muthirai (2009)/Om Shanthi Om.mp3',
    'Muthirai (2009)/Uyire Uyire.mp3',
    'Naan Mahaan Alla (2010)/Iragai Pole.mp3',
    'Naan Mahaan Alla (2010)/Oru Maalai Neram.mp3',
    'Naan Mahaan Alla (2010)/Theivam Illai.mp3',
    'Naan Mahaan Alla (2010)/Va Va Nilava Pudich.mp3',
    'Naan Mahaan Alla (2010)/Va Va Nilava Pudichi II.mp3',
    'Nandha (2001)/Amma Endralle.mp3',
    'Nandha (2001)/Engengo Kaalgal Sellum.mp3',
    'Nandha (2001)/Kalli Adi Kalli.mp3',
    'Nandha (2001)/Maayane Andha.mp3',
    'Nandha (2001)/Mun Paniyaa.mp3',
    'Nandha (2001)/Or Aayiram Yaanai.mp3',
    'Oru Kalluriyin Kathai (2005)/Dalappa Kattuda.mp3',
    'Oru Kalluriyin Kathai (2005)/Geetha Mala.mp3',
    'Oru Kalluriyin Kathai (2005)/Kadhal Yenbathu.mp3',
    'Oru Kalluriyin Kathai (2005)/Kangal Kalangida.mp3',
    'Oru Kalluriyin Kathai (2005)/Kangal Kandathu Kangal.mp3',
    'Oru Kalluriyin Kathai (2005)/Kangal Kandathu.mp3',
    'Oru Kalluriyin Kathai (2005)/Pangu Podu.mp3',
    'Oru Kalluriyin Kathai (2005)/Unakku Yendru Oruthi.mp3',
    'Paiyaa (2009)/Adada Mazhaida.mp3',
    'Paiyaa (2009)/En Kadhal Solla.mp3',
    'Paiyaa (2009)/Poongatre Poongatre.mp3',
    'Paiyaa (2009)/Suthuthe Suthuthe Bhoomi.mp3',
    'Paiyaa (2009)/Thuli Thuli Mazhaiyaai.mp3',
    'Paiyaa (2009)/Yedho Ondru Ennai.mp3',
    'Paruthiveeran (2006)/Ariyadha Vayasu.mp3',
    'Paruthiveeran (2006)/Iayyayo.mp3',
    'Paruthiveeran (2006)/Nathaswaram Bit.mp3',
    'Paruthiveeran (2006)/Sari Kama Pathan.mp3',
    'Paruthiveeran (2006)/Tanka Dunga.mp3',
    'Paruthiveeran (2006)/Vuroram Puliamaram.mp3',
    'Pathinaaru (2010)/Ada Da En Meethu.mp3',
    'Pathinaaru (2010)/Kaattu Chedikku.mp3',
    'Pathinaaru (2010)/Theme Music.mp3',
    'Pathinaaru (2010)/Vaanam Namadhe.mp3',
    'Pathinaaru (2010)/Yaar Solli Kadhal.mp3',
    'Pattiyal (2006)/Dei Namma Melam Edutha.mp3',
    'Pattiyal (2006)/Kannai Vittu Kann Imaigal (Remix).mp3',
    'Pattiyal (2006)/Kannai Vittu Kann Imaigal.mp3',
    'Pattiyal (2006)/Namma Kattula Mazhai Peiyuthu.mp3',
    'Pattiyal (2006)/Poga Poga Boomi Virikirathe.mp3',
    'Pattiyal (2006)/Yedhedo Ennangal Vandhu.mp3',
    'Perazhagan (2004)/Ambuli Mama.mp3',
    'Perazhagan (2004)/Kaadhalukku.mp3',
    'Perazhagan (2004)/Kaatru Enbatha.mp3',
    'Perazhagan (2004)/Ore Oru Piravi.mp3',
    'Perazhagan (2004)/Oru Azghana.mp3',
    'Pesu (2011)/En Per Devathai.mp3',
    'Pesu (2011)/Ithayam Pesuthey.mp3',
    'Pesu (2011)/Kettimelam.mp3',
    'Pesu (2011)/Unthan Varthaiyil.mp3',
    'Pesu (2011)/Vennira Iravugal.mp3',
    'Poojai (2014)/Devathai.mp3',
    'Poojai (2014)/Ippadiye.mp3',
    'Poojai (2014)/Odi Odi.mp3',
    'Poojai (2014)/Soda Bottle.mp3',
    'Poojai (2014)/Uyire.mp3',
    'Poojai (2014)/Verarum.mp3',
    'Poovellam Kettuppar (1999)/CBI Enge Theda.mp3',
    'Poovellam Kettuppar (1999)/Chudithar Aninthu Vantha.mp3',
    'Poovellam Kettuppar (1999)/Irava Pagala.mp3',
    'Poovellam Kettuppar (1999)/Poothathu Poothathu.mp3',
    'Poovellam Kettuppar (1999)/Poova Poova Poove.mp3',
    'Poovellam Kettuppar (1999)/Poove Poove (M).mp3',
    'Poovellam Kettuppar (1999)/Senyoreeta Senyoreeta.mp3',
    'Poovellam Kettuppar (1999)/Sevvanam Vetkam Kondathu.mp3',
    'Pop Carn (2002)/Amma Inge Vaa.mp3',
    'Pop Carn (2002)/En Isaikku.mp3',
    'Pop Carn (2002)/Kadhalagi Kaninthu.mp3',
    'Pop Carn (2002)/Naan Vachen Lesa.mp3',
    'Pop Carn (2002)/Poikaal Kudhirai.mp3',
    'Pop Carn (2002)/Poovaitha Poovil.mp3',
    'Pop Carn (2002)/Poovellam Paaraddum.mp3',
    'Pop Carn (2002)/Popcarn (Theme Music).mp3',
    'Pudhiya Geethai (2003)/Annamalai.mp3',
    'Pudhiya Geethai (2003)/Manase.mp3',
    'Pudhiya Geethai (2003)/Mercury Poove.mp3',
    'Pudhiya Geethai (2003)/Naan Odum.mp3',
    'Pudhiya Geethai (2003)/Vasiyakara.mp3',
    'Pudhiya Geethai (2003)/Vasiyakari.mp3',
    'Pudhukottaiyilirundhu Saravanan (2003)/Baby Baby.mp3',
    'Pudhukottaiyilirundhu Saravanan (2003)/Malargale.mp3',
    'Pudhukottaiyilirundhu Saravanan (2003)/Naatu Sarakku.mp3',
    'Pudhukottaiyilirundhu Saravanan (2003)/Pudhu Kadhal.mp3',
    'Pudhukottaiyilirundhu Saravanan (2003)/Pudhukkotai Saravanan.mp3',
    'Pudhukottaiyilirundhu Saravanan (2003)/Where Do We Go.mp3',
    'Pudhupettai (2005)/Clash Of The Titans-The War Cry.mp3',
    'Pudhupettai (2005)/Enga Yeriya-Our Story.mp3',
    'Pudhupettai (2005)/Going Thru Emotions Prelude.mp3',
    'Pudhupettai (2005)/Neruppu Vaayinil-Peek Into Assasins Life.mp3',
    'Pudhupettai (2005)/Oru Naalil-Composers Dream Mix.mp3',
    'Pudhupettai (2005)/Oru Naalil-It All Comes Down To This.mp3',
    'Pudhupettai (2005)/Pudhupettai Main Theme-Survival Of The Fittest.mp3',
    'Pudhupettai (2005)/Pulpesum Poo Pesum Gangsters Marriage Party.mp3',
    'Pudhupettai (2005)/Selling Dope-The Beginning.mp3',
    'Pudhupettai (2005)/Varriyaa-Night Life.mp3',
    'Punnagai Poove (2002)/En Kadhal.mp3',
    'Punnagai Poove (2002)/Jogging Seyyum.mp3',
    'Punnagai Poove (2002)/Oru Poongili.mp3',
    'Punnagai Poove (2002)/Siragaki Ponathe.mp3',
    'Punnagai Poove (2002)/Thiruvallikeni.mp3',
    'Punnagai Poove (2002)/Vaanam Thoovum Poo.mp3',
    'Punnagai Poove (2002)/Venus Venus.mp3',
    'Punnagai Poove (2002)/Yeno Uyir.mp3',
    'Raam (2005)/Aarariraro.mp3',
    'Raam (2005)/Boom Boom.mp3',
    'Raam (2005)/Manithan Solkindra.mp3',
    'Raam (2005)/Nizhalinai Nijamum.mp3',
    'Raam (2005)/Vidikindra Pozhuthu.mp3',
    'Raam (2005)/Yaaro Arivaal.mp3',
    'Rajapattai (2011)/Laddu Laddu Rendu Laddu.mp3',
    'Rajapattai (2011)/Paniye Paniye.mp3',
    'Rajapattai (2011)/Podi Paiyyan Polave.mp3',
    'Rajapattai (2011)/Podi Paiyyan.mp3',
    'Rajapattai (2011)/Villaathi Villan.mp3',
    'Rishi (2000)/Jumbo Idhu Kaathal.mp3',
    'Rishi (2000)/Kaatrodu Puyalaai.mp3',
    'Rishi (2000)/Nilavai Konjam.mp3',
    'Rishi (2000)/Oh Mane Mane(girl.mp3',
    'Rishi (2000)/Oh Mane Mane.mp3',
    'Rishi (2000)/Vaa Vaa Poove.mp3',
    'Samar (2012)/Azhago Azhagu.mp3',
    'Samar (2012)/Oru Kannil Vegam.mp3',
    'Samar (2012)/Poikkaal Kuthirai.mp3',
    'Samar (2012)/Rajaavin Thottathil.mp3',
    'Samar (2012)/Vellai Mayil.mp3',
    'Sandakozhi (2005)/Dhavanipotta Deepavali.mp3',
    'Sandakozhi (2005)/Ennamo Nadakkirathe.mp3',
    'Sandakozhi (2005)/Gumthalakkadi Gana.mp3',
    'Sandakozhi (2005)/Ketta Kodukkira Boomi.mp3',
    'Sandakozhi (2005)/Mundasu Sooriyane.mp3',
    'Saroja (2008)/Aaja Meri Soniye.mp3',
    'Saroja (2008)/Cheeky Cheeky.mp3',
    'Saroja (2008)/Dosth Bada Dosth.mp3',
    'Saroja (2008)/Kodana Kodi.mp3',
    'Saroja (2008)/My Life.mp3',
    'Saroja (2008)/Nimirnthu Nil.mp3',
    'Sarvam (2009)/Adada Vaa.mp3',
    'Sarvam (2009)/Kaatrukullae.mp3',
    'Sarvam (2009)/Neethane.mp3',
    'Sarvam (2009)/Siragugal.mp3',
    'Sarvam (2009)/Sutta Suriyane.mp3',
    'Sarvam (2009)/Theme Music.mp3',
    'Satham Podathey (2007)/Azhagu Kutti Chellam.mp3',
    'Satham Podathey (2007)/Entha Kuthirayil.mp3',
    'Satham Podathey (2007)/Kadhal Periyadha.mp3',
    'Satham Podathey (2007)/O Indha Kaadhal.mp3',
    'Satham Podathey (2007)/Pesugiren Pesugiren.mp3',
    'Silambattam (2008)/Machaan Machaan.mp3',
    'Silambattam (2008)/Nallamdhana.mp3',
    'Silambattam (2008)/Silambattam.mp3',
    'Silambattam (2008)/Vechikkava (Remix).mp3',
    'Silambattam (2008)/Where is the Party.mp3',
    'Siva Manasula Sakthi (2009)/Eppadio Mattikiten.mp3',
    'Siva Manasula Sakthi (2009)/MGR Illenga.mp3',
    'Siva Manasula Sakthi (2009)/Oru Adangapidari.mp3',
    'Siva Manasula Sakthi (2009)/Oru Kal II.mp3',
    'Siva Manasula Sakthi (2009)/Oru Kal.mp3',
    'Siva Manasula Sakthi (2009)/Oru Paarvaiyil.mp3',
    'Siva Manasula Sakthi (2009)/Thithikum Theeai.mp3',
    'Thaamirabharani (2006)/Karuppaana Kaiyale.mp3',
    'Thaamirabharani (2006)/Kattabomman Oorenakku.mp3',
    'Thaamirabharani (2006)/Thaaliyae Thevaiyillai.mp3',
    'Thaamirabharani (2006)/Thiruchendhuru Muruga.mp3',
    'Thaamirabharani (2006)/Vaartha Onnu.mp3',
    'Thanga Meenkal (2013)/Aanandha Yazhai.mp3',
    'Thanga Meenkal (2013)/First Last.mp3',
    'Thanga Meenkal (2013)/Nathi Vellam.mp3',
    'Thanga Meenkal (2013)/Yaarukkum Thozhan Illai.mp3',
    'Theeradha Vilaiyattu Pillai (2009)/En Aasai Ethiraliye.mp3',
    'Theeradha Vilaiyattu Pillai (2009)/En Jannal Vandha.mp3',
    'Theeradha Vilaiyattu Pillai (2009)/Oru Punnagai Thane.mp3',
    'Theeradha Vilaiyattu Pillai (2009)/Poo Mudhal Pen Varai V2.mp3',
    'Theeradha Vilaiyattu Pillai (2009)/Poo Mudhal Pen Varai.mp3',
    'Theeradha Vilaiyattu Pillai (2009)/Teriyaamaley Toleygiyren.mp3',
    'Theeradha Vilaiyattu Pillai (2009)/Theeratha Vilayattu.mp3',
    'Theeradha Vilaiyattu Pillai (2009)/U1 Introduction.mp3',
    'Thennavan (2003)/Adi Sami Sathiyamma.mp3',
    'Thennavan (2003)/Desakaatrae Desakaatrae.mp3',
    'Thennavan (2003)/Desakaatrae.mp3',
    'Thennavan (2003)/Englishil Paadina.mp3',
    'Thennavan (2003)/Vatta Vatta.mp3',
    'Thennavan (2003)/Vinothanae Vinothanae II.mp3',
    'Thennavan (2003)/Vinothanae Vinothanae.mp3',
    'Thillalangadi (2010)/Ding Ding.mp3',
    'Thillalangadi (2010)/Idhayam Karaikirathe.mp3',
    'Thillalangadi (2010)/Memory Loss.mp3',
    'Thillalangadi (2010)/Pattu Pattu.mp3',
    'Thillalangadi (2010)/Pootta Paathadhum.mp3',
    'Thillalangadi (2010)/Sol Pechu.mp3',
    'Thillalangadi (2010)/Thothu Ponen.mp3',
    'Thillu Mullu (2013)/Aaja Aaja.mp3',
    'Thillu Mullu (2013)/Kaipesi En Kooda.mp3',
    'Thillu Mullu (2013)/Raagangal Pathinaru.mp3',
    'Thillu Mullu (2013)/Thillu Mullu.mp3',
    'Thimiru (2006)/Kattikko Rappa Rappa.mp3',
    'Thimiru (2006)/Maana Madurai.mp3',
    'Thimiru (2006)/Mani Mani.mp3',
    'Thimiru (2006)/Oppurane Oppurane.mp3',
    'Thimiru (2006)/Theme Music.mp3',
    'Thimiru (2006)/Thithikkara Vayasu.mp3',
    'Thirudan Police (2014)/Deivam Enbadhenna (I).mp3',
    'Thirudan Police (2014)/Deivam Enbadhenna (II).mp3',
    'Thirudan Police (2014)/Ennodu Va.mp3',
    'Thirudan Police (2014)/Moodu Panikkul.mp3',
    'Thirudan Police (2014)/Pesadhe.mp3',
    'Thottal Poo Malarum (2007)/Arabu Naade.mp3',
    'Thottal Poo Malarum (2007)/Ennai Pidicha.mp3',
    'Thottal Poo Malarum (2007)/Kadatharan Naan Unnai.mp3',
    'Thottal Poo Malarum (2007)/Vaadi Vambu Pennae.mp3',
    'Thottal Poo Malarum (2007)/Valaiyal Karangalai.mp3',
    'Thottal Poo Malarum (2007)/Vittal Suriyanai.mp3',
    'Thulluvadho Ilamai (2001)/Idhu Kadhala.mp3',
    'Thulluvadho Ilamai (2001)/Kanmuney Ethanai Nilavu.mp3',
    'Thulluvadho Ilamai (2001)/Katrukku Katrukku.mp3',
    'Thulluvadho Ilamai (2001)/Neruppu Koothadikuthu.mp3',
    'Thulluvadho Ilamai (2001)/Theenda Theenda (Duet).mp3',
    'Thulluvadho Ilamai (2001)/Theenda Theenda (Solo).mp3',
    'Thulluvadho Ilamai (2001)/Theepiditha Kangal.mp3',
    'Thulluvadho Ilamai (2001)/Theme Music (Instrumental).mp3',
    'Thulluvadho Ilamai (2001)/Vaanam Oru.mp3'
];

// Keep track of song
let songIndex = Math.floor((Math.random() * songs.length) + 1);

// Initially load song details into DOM
loadSong(songs[songIndex]);

// Update song details
function loadSong(song) {
    title.innerText = song.split('/')[0] + '\n' + song.split('/')[1];
    audio.src = `music/${song}`;
    cover.src = `music/${song.split('/')[0]}/offset.jpg`;
}

// Play song
function playSong() {
    musicContainer.classList.add('play');
    playBtn.querySelector('i.fas').classList.remove('fa-play');
    playBtn.querySelector('i.fas').classList.add('fa-pause');

    audio.play();
}

// Pause song
function pauseSong() {
    musicContainer.classList.remove('play');
    playBtn.querySelector('i.fas').classList.add('fa-play');
    playBtn.querySelector('i.fas').classList.remove('fa-pause');

    audio.pause();
}

// Previous song
function prevSong() {
    songIndex--;

    if (songIndex < 0) {
        songIndex = songs.length - 1;
    }

    loadSong(songs[songIndex]);

    playSong();
}

// Next song
function nextSong() {
    songIndex = Math.floor((Math.random() * songs.length) + 1);

    if (songIndex > songs.length - 1) {
        songIndex = 0;
    }

    loadSong(songs[songIndex]);

    playSong();
}

// Update progress bar
function updateProgress(e) {
    const { duration, currentTime } = e.srcElement;
    const progressPercent = (currentTime / duration) * 100;
    progress.style.width = `${progressPercent}%`;
}

// Set progress bar
function setProgress(e) {
    const width = this.clientWidth;
    const clickX = e.offsetX;
    const duration = audio.duration;

    audio.currentTime = (clickX / width) * duration;
}

// Event listeners
playBtn.addEventListener('click', () => {
    const isPlaying = musicContainer.classList.contains('play');

    if (isPlaying) {
        pauseSong();
    } else {
        playSong();
    }
});

// Change song
prevBtn.addEventListener('click', prevSong);
nextBtn.addEventListener('click', nextSong);

// Time/song update
audio.addEventListener('timeupdate', updateProgress);

// Click on progress bar
progressContainer.addEventListener('click', setProgress);

// Song ends
audio.addEventListener('ended', nextSong);